# config/settings.yaml

project_root: "/home/sr1160/Documents/Postdoc/Projects/Project_ML_Kernels/Code/ml_electronic_friction"

system_identifier: "surface_hopping"
data_root: "data"
results_root: "results"
source_root: "source"

results_subdirs:
  el_forces: "el_forces"
  steady_state: "steady_state"
  transient: "transient"

#--------------------
# Physical parameters
# -------------------

# Energy parameters are in eV
# Voltage is in V
# Coordinates are dimensionless
# Temperature is in Kelvin

phys_param:
  molecule_lead_coupling: 100
  temperature: 300
  el_energy: 100
  vib_freq: 30
  elvib_coup: 30
  units_type: "dimensionless"
  potential:
    type: "harmonic"
  voltage: 0

#----------------------------
# Default plotting parameters 
# ---------------------------

plotting:
  linewidth: 2
  font_family: 'serif'
  use_tex: true
  axes_linewidth: 2
  label_fontsize: 30
  tick_labelsize: 20
  tick_length: 6
  tick_width: 2

#----------------------------
# Surface hopping simulation 
# parameters 
# ---------------------------

simulation:
  phys_ic_type: WIGNER
  aux_ic_type: STATIONARY
  n_traj: 20
  ic_mean: [0,0]
  ic_var: [0.03,0.03]
  init_vib_temp: 300
  dt: 2
  n_timesteps: 5000
  n_cores: 20
  base_seed: 42
