# config/settings.yaml

# project_root: "/home/samuel/Documents/Postdoc/Projects/Project_ML_friction_kernels/Code/ml_electronic_friction"
project_root: "/home/sr1160/Documents/Postdoc/Projects/Project_ML_Kernels/Code/ml_electronic_friction"

sim_id_root: "surface_hopping"
data_root: "data"
results_root: "/home/sr1160/Documents/Postdoc/Projects/Project_ML_Kernels/Results/surface_hopping"
# results_root: "/home/samuel/Documents/Postdoc/Projects/Project_ML_Kernels/Results"
source_root: "source"

results_subdirs:
  trajectories: "trajectories"
  ensemble_av: "ensemble_av"
  plots: "plots"

#--------------------
# Physical parameters
# -------------------

# Energy parameters are in eV
# Voltage is in V
# Coordinates are dimensionless
# Temperature is in Kelvin

phys_param:
  molecule_lead_coupling: 0.01
  temperature: 300
  el_energy: 0.015
  elvib_coup: 0.01
  units: "dimensionless"
  potential:
    type: "harmonic"
    vib_freq: 0.03
    mass: 1 # Only not equal to 1 if units are not "dimensionless"
  voltage: 0

#----------------------------
# Default plotting parameters 
# ---------------------------

plotting:
  linewidth: 2
  font_family: 'serif'
  use_tex: true
  axes_linewidth: 2
  label_fontsize: 30
  tick_labelsize: 20
  tick_length: 6
  tick_width: 2

#----------------------------
# Surface hopping simulation 
# parameters 
# ---------------------------

simulation:
  ic_rand_rng: true
  ic_rng: 42
  ic_type: "wigner"
  n_traj: 10
  ic_mean: [0,0]
  ic_var: [0.03,0.03]
  ic_el_weights: [0,1]
  init_vib_temp: 300
  dt: 1
  n_timesteps: 50000
  base_seed: 42
  n_threads: 20
  traj_seed: 1709
